// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'container': string;
  'root': string;
  'rotate': string;
  'subTitle': string;
  'title': string;
  'waiting': string;
}
export const cssExports: CssExports;
export default cssExports;
