// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LinksContainer': string;
  'activeImg': string;
  'rotate3d': string;
}
export const cssExports: CssExports;
export default cssExports;
