// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CenterMain': string;
  'mainPage': string;
}
export const cssExports: CssExports;
export default cssExports;
