// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TextContainer': string;
  'coursive': string;
  'secondaryText': string;
}
export const cssExports: CssExports;
export default cssExports;
