// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Slide': string;
  'SliderContainer': string;
  'SliderContainerItem': string;
  'SliderContainerMain': string;
  'SliderNote': string;
  'Title': string;
  'WaitingSlide': string;
  'rotate': string;
}
export const cssExports: CssExports;
export default cssExports;
